task: detection

num_classes: 3
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder_rgb: ./FLIR_Aligned/images_rgb_train/data
    ann_file_rgb: ./FLIR_Aligned/images_rgb_train/train.json
    img_folder_ir: ./FLIR_Aligned/images_thermal_train/data
    ann_file_ir: ./FLIR_Aligned/images_thermal_train/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder_rgb: ./FLIR_Aligned/images_rgb_test/data
    ann_file_rgb: ./FLIR_Aligned/images_rgb_test/val.json
    img_folder_ir: ./FLIR_Aligned/images_thermal_test/data
    ann_file_ir: ./FLIR_Aligned/images_thermal_test/val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  drop_last: False